\documentclass[12pt,letterpaper]{report}
\renewcommand{\familydefault}{\sfdefault}
\usepackage[font=sf]{floatrow}
\begin{document}

\thispagestyle{empty}                           

\section*{No Enrollment Information}
We cannot generate a report for your school; we either do not have enrollment data for your school, or our enrollment data does not match the grades reported in your survey. We apologize for the inconvenice. 

\end{document}